### ISSUE TITLE
Survey123 Bug? Image within a text / note open and then cannot be closed.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#102]
"Bug: when you click on the picture of search definitions inside “Survey instructions”, there’s no way to go back without force quitting the app. This is on iOS 14.3." - Collin Grove

**Comment by pjdohertygis** [comment]
Confirming I can replicate in t_v8a ![image](https://user-images.githubusercontent.com/4256979/102387611-74efb980-3f85-11eb-861c-dc052b99a766.png) on an iPhone
 Clicking on this image 
![image](https://user-images.githubusercontent.com/4256979/102387693-8d5fd400-3f85-11eb-8336-ebfc6ecc696c.png)

**Comment by pjdohertygis** [comment]
Katie Breland confirms this as well.

**Comment by jdokemaps** [comment]
This seems to be an issue with this particular image....maybe because it is a large portrait image? The other images in that section can be enlarged and then a "back" arrow appears to take you back to the survey. For now, I am going to remove this image because the text is pretty small and a lot of people aren't able to read it anyways.

**Comment by IsmaelInRedlands** [comment]
While this is caused by the size of the image relative to the size of the device's screen, you may want to open a Tech Support incident. The Survey123 app should take of this and allow you to use the back button regardless of the size of the image.  If you share the XLSForm with the image with Tech Support that would help.

**Comment by pjdohertygis** [comment]
@afackler do you have time to report this bug quickly to Esri Support? Should be straightforward to report.

**Comment by pjdohertygis** [comment]
We worked around by providing a link instead of embedding the graphic.
