### ISSUE TITLE
QuickCapture Project User Input = Survey123 Favorites

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#136]
Once the QuickCapture Team allows for multiple project user inputs we need to know which three questions to ask. Until we find a way to move to team / squad based logins I suggest the following based on feedback:

1) Team Name
2) Squad / Device #
3) Team User / Operator - the person filling out the form (we had this in v7, but people really want us to add it back in for accountability)

Then... using the linked button you can (hopefully) fill out the Event Details / Favorites for Survey123. This will save a lot of time. 

@IsmaelInRedlands - will this approach be supported? I guess you will need to have a User Interface for matching up multiple project user inputs in QuickCapture?

**Comment by grover556** [comment]
If we can get to the point where the teams that access the survey have standardized account names, instead of team name, we can set the search type. We wouldn't have a bunch of wasted screen real estate with different search types - just one button to start/stop the track log.

Even if logins aren't standardized, we could use coded values to link accounts to teams.

I agree with bringing back the team_user field. Having the user's last name really helps to track the person down when we have questions about points.

**Comment by pjdohertygis** [comment]
Partially implemented, but only will work when accessing Survey123 from QuickCapture.
