### ISSUE TITLE
Daily Archive Notebook

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#141]
@afackler has created a "daily archive" Jupyter Notebook

FEMA Internal: https://fema.maps.arcgis.com/home/item.html?id=ba5ce30f0d59436298feedf700fa3e2b

Adam can you share the code here so others can take a look?

**Comment by afackler** [comment]
Attached is the Jupyter notebook file. It can be brought into ArcGIS Online by downloading this file, then going to "Add Item" and "From your computer". It will automatically upload as a Jupyter notebook.

I am still working with Esri to figure out the moving data issue. Right now the script will export every specified feature layer as a geodatabase to the root folder in ArcGIS Online. I will post updates on any progress or any changes to the code.

[ArchiveData.zip](https://github.com/pjdohertygis/WideAreaSearchTemplates/files/6694658/ArchiveData.zip)

**Comment by pjdohertygis** [comment]
Hit one issue yesterday where it published the tracklog a few times in one session and one of the gdb was corrupted. Ran it a second time with no issues. 

Also, is there a way to improve the item and file naming? 

![image](https://user-images.githubusercontent.com/4256979/123096493-25d78500-d3fd-11eb-8380-b2beac067754.png)

**Comment by afackler** [comment]
Not sure why the gbd would become corrupt... did it run like normal? Any error codes?

Yes, we can change the naming scheme. What do you want it to be?

**Comment by pjdohertygis** [comment]
@afackler any major updates on our Jupyter approach?

**Comment by afackler** [comment]
I did find a workaround for the issue of the data not moving to the desired folder and implemented it into the USAR archive script a while back. After testing with the sandbox data, the script works well with the workaround with little changes overall. Otherwise no other major updates on the tech end. As for sharing the script, I am working on getting the code into a public repository to share out on NAPSG's github. I will have it released before our prep tech talk on Dec 9.

**Comment by pjdohertygis** [comment]
Ok sounds good - I'll go ahead and close this!
