### ISSUE TITLE
Survey123: Z-values?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#150]
From MO-TF1: More of a general mapping "Z" question that I am researching to better support mapping for large building/structure search vertically. How has v8_WAS data been looking when teams have been in GPS deprived areas like as they work within voids in the garage?  We are only capturing XY if I recall.   Maybe we need v9_WAS to capture X Y and Z information from the GPS and add a Z-level field that users can enter "floor/level" info so we can extrude the data in 3d to show heights/level of their search progress. Lots of work has been done on this on the NENA e911 side - https://www.fcc.gov/public-safety-and-homeland-security/policy-and-licensing-division/911-services/general/location-accuracy-indoor-benchmarks

**Comment by pjdohertygis** [comment]
I suspect that we would want two approaches. 

Calculated Z - whatever we can get from the device and GPS. Bad Elf's or other devices *may* help with this.
Derived Z - whatever information we can get from the person entering. Floor number?

**Comment by jwarzi** [comment]
For when building that is still standing or to some extend collapsed but still "in levels", third approach could pre-load local or US National Address Data with vertical aware address point data to be assignments for searching.  NENA and US NAD has a floor field that if populated could give us the "heights".  Bigger issue is positional accuracy when a team is inside with no GPS signal and the ESRI map apps will not allow mapping because of the minimum positional accuracy required/setting.

https://www.transportation.gov/sites/dot.gov/files/docs/mission/gis/national-address-database/308816/nad-schema-v2.pdf
https://www.nena.org/page/NG911GISDataModel

**Comment by IsmaelInRedlands** [comment]
@pjdohertygis 
If the feature layer as Z enabled in the SHAPE field, Survey123, QuickCapture and Field Maps should automatically record the Z value.
If you are creating a new layer with Survey123, check this article: https://community.esri.com/t5/arcgis-survey123-blog/working-with-z-values-in-survey123/ba-p/895011

**Comment by pjdohertygis** [comment]
It looks like our current v8 waypoint layer does not have Z enabled so we cannot easily implement the Shape approach. 

![image](https://user-images.githubusercontent.com/4256979/143080754-94d96f01-9719-4cfe-affa-27f6ef0181ef.png)

Let's continue the discussion on this within the Cadre.
