### ISSUE TITLE
QuickCapture: Linked Surveys do not give the option to install Survey123

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#213]
From Dave Weber - "Currently all of the Survey123 project launch buttons located in QuickCapture | Additional Apps and Forms do not point you to the app store on your smart device if the Survey123 app is not installed first. 

QuickCapture from the QR code and Field Maps currently direct you to the app store.  I think the Survey123 buttons should direct you to the app store if you don’t have it installed before you select the button." 

This is not something we have control over but, we can ask Esri for an enhancement. In the meantime, we just have to remind StS and others they need to have Survey123 installed. Something the TIS should have already done if it is a device from the cache.

**Comment by IsmaelInRedlands** [comment]
Hi @pjdohertygis . Thanks for sharing this . This is caused by the format of the link, which follows the arcgis-survey123:: pattern instead of https://survey123.arcgis.app. We need to review why we chose to go with arcgis-survey123:: in the past. 
 I added a note in our internal repo to evaluate switching to app links. In the meantime, if you create links using  https://survey123.arcgis.app users will get instructions to install the app. Check https://doc.arcgis.com/en/survey123/reference/integratewithotherapps.htm
