### ISSUE TITLE
QuickCapture: Drop-downs for Project User Input are not cached?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#221]
In our QuickCapture projects, the first project user input does not cache the answer. Is this by design? 
https://arcg.is/14fK4

![image](https://user-images.githubusercontent.com/4256979/175341598-368ee629-c728-4d0f-942e-64f296378351.png)

Is this something that won't work for dropdowns? For a long list this can be cumbersome.

**Comment by IsmaelInRedlands** [comment]
The issue is dropdowns.  The current design is for QuickCapture **not** to auto-populate the input. Instead QuickCapture simply provides a list of values previously entered so you can quickly tap on any of them to save you from manually typing again.
With lists, we do not show a list of previous entries because the list is already there so you can also just tap on the choice.
Hope this makes sense. 
It seems to me like you would want QuickCapture to remember previous values and use them as default. That is a valid request, but the software does not do that right now.  What you are experiencing is what we expect to happen with the current design.
