### ISSUE TITLE
[BUG] QuickCapture: To add a project, for some users the + sign is not showing up?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#222]
I will try to get device and app version details, but it was about 15 people in the course that I am in today.

**Comment by JohnHasthorpe** [comment]
@pjdohertygis 

If this happens, go into settings=>press and hold the about button for 5 seconds=>Settings=>Show console (switch on)
This will reveal an orange button/floating UI
Press it and go to the Systems tab. This should provide useful information. 

The issue happens if the app thinks the device is not connected to the portal.

**Comment by pjdohertygis** [comment]
Ok will try to catch this next time!

**Comment by pjdohertygis** [comment]
I have not seen this in a while and will close unless it pops up again.
