### ISSUE TITLE
WAS Form: Add Waypoint Category for 911 OR have a 911 Call Layer?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#63]
Add a new waypoint category for 911 calls for service - this is based on request from TX-TF1, check with Katie B for more details.

Also see https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/57****

**Comment by pjdohertygis** [comment]
Should this be a new waypoint or a separate reference layer?

**Comment by pjdohertygis** [comment]
We could use this symbol for 911 calls? https://napsg-web.s3.amazonaws.com/symbology/data/PNG9/lifelines/Communications/communications_911-dispatch-red-halo_64x64.png

**Comment by pjdohertygis** [comment]
Jared and Paul discussed, this has come up several times and should be implemented. 

Should it go under incident support or human interaction? We are leaning towards human interaction so it gets filtered out of views with the other human interactions.

**Comment by jdokemaps** [comment]
911 Call implemented as a waypoint. I used 
![image](https://user-images.githubusercontent.com/52461518/99454984-69589680-28e4-11eb-854a-16d53da769dd.png) as the symbol because it is a circle for incident data and no colored halo so we can "stack" symbols and see the status of that waypoint.

**Comment by pjdohertygis** [comment]
"As I spoke on the call, I’m not a fan of adding 911 Call, as this is ambiguous, and the default to “Needs Followup” is a little confusing. The only deployments I’ve run 911 calls on were water rescue missions where we are responding with FD/PD. In my mind, that’s a targeted search, that we’ve completed while on site." - Colin Grove 

Could we use the existing targeted search icon? Let's get feedback from Search Advisory Group?

**Comment by pjdohertygis** [comment]
"I have done multiple 911 calls but if everyone wants to use the “Targeted Search” icon instead that’s fine as long as that is how it is trained to be used.  Most of the “Targeted Searches” I have done for FEMA were not urgent like a 911 call would be." - Katie Breland TX-TF1

**Comment by pjdohertygis** [comment]
This could be redundant as well - could we simply use Waypoint: Targeted Search Follow-up: Needs Follow-up?

**Comment by t-mahon** [comment]
Pretty sure this is a decided issue, I can say from the NY-TF1 and FDNY SOCTF point of view, we have used this for directing teams already in the field and members are adept at tracking it down and performing searches from that point.  I think using it for 911 calls is a natural evolution and good use of an existing waypoint since we want to keep the symbology tight.
I do know our field units aren't the best at changing the symbol on the fly.  That might be best done by a TIS/PLANS back at the BOO.  Having the original waypoint flag in there will help.  Just need to decide if field members are dropping points on top of or radioing changes back.  Obviously the gold standard is getting them to edit in the field eventually.
For future consideration we could add a subtype flag similar to what Jared is doing for the 'Searched' waypoint.  Not so much for the field members but so that TIS, IST or whoever is feeding the targets can classify them. (911, Other Agency, etc)  In PR we were receiving targets from other teams and government agencies to perform wellness checks, this might be a way to quantify those as targeted searches.

**Comment by pjdohertygis** [comment]
Keeping targeted search icon with follow-up status critical to life safety as solution.

**Comment by t-mahon** [comment]
For the 911 calls, if we append them as 'Targeted Search' and 'needs follow up' does that solve the issue of not adding to the schema but keeping them easily accessible in the existing layers?  When a call is actioned the members can either edit the Targeted Search, or more likely, just drop the disposition icons on top. (Rescue, Assisted, etc)

I think the big lift here is going to be how we import the 911 calls.  And thinking that happens above the TFs at the IST or Remote Support level.  

I'm only familiar with NYC 311/911 data and it's not the cleanest or most intuitive.  That being said, if some of the state resources (LA. TX, FL) can provide sample data maybe we can see what we're dealing with before crunch time.

**Comment by pjdohertygis** [comment]
Putting on the Planner backlog, no action needed at this time https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:WQQU-GLBt5PUCaamNqbuPkjLTt8tsICkDpvbXmW_T541@thread.tacv2_p_PQ35VCIfNU2Eeb0TdloUJmQADk0f_h_1636482835657?tenantId=e78bd32c-e20a-42de-9956-6429fc41698d&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FCEvOHHbcfUuXhT8UVn36K2QAD7K6%22%2C%22channelId%22%3A%2219%3AWQQU-GLBt5PUCaamNqbuPkjLTt8tsICkDpvbXmW_T541%40thread.tacv2%22%7D
