### ISSUE TITLE
Implement Spike and Survey123 for plotting point locations at a distance

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#74]
Real-world problem: Mapping points that you cannot access (e.g., from a helicopter, flooded house from a vehicle, etc.

I am able to setup basic measurements in Spike/Survey123, but plotting points will require some configuration that is beyond my capability. 

Measurement of objects may be useful for structural engineers!
Video: https://www.youtube.com/watch?v=82YPfDxGL3Q

General doc: https://doc.arcgis.com/en/survey123/desktop/create-surveys/xlsformsappearance.htm#ESRI_SECTION1_BA93396F739D4E53B7CD46401495C6BC

See Estimate Locations notes on this page for next steps and challenges https://www.esri.com/arcgis-blog/products/survey123/announcements/announcing-support-for-spike-in-survey123-for-arcgis/

**Comment by afackler** [comment]
This process does not place a point at a projected location, but returns the xy or a projected location using the calculation: pulldata("@exif", ${spike}, "gpsdestlatitude". The calculation can be put into a note field and later extracted from the data. Upon testing, results were not accurate likely due to cell phone compass limitations.

**Comment by pjdohertygis** [comment]
Ok after doing some testing - I think Spike is a great tool for taking measurements and may be useful for US&R Structure Specialists. But, it does not look like the right tool for "projecting" waypoints. As stated in the documentation, it relies too heavily on the device compass. It is easier just to drag the pin and provide offline basemaps when needed. So we can close this issue.
